DA Project 1 - T02G06: algorithms/AlternativeRoutes.cpp File Reference
AlternativeRoutes.cpp File Reference
#include "EnvironmentallyFriendly.cpp"
Functions
template<class T>
void copyIfBetter (std::list< T > &path1, T &parkingNodeId1, int &walkingTime1, int &drivingTime1, std::list< T > &path2, T &parkingNodeId2, int &walkingTime2, int &drivingTime2)
Copies path 2, parking node 2, walking time 2, and driving time 2 to path 1, parking node 1, walking time 1 and driving time 1 if path 2 is better (smaller total cost) in O(L) where L is the size of path2.
template<class T>
void getBestAlternative (const Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, const int maxWalkTime, const std::unordered_set< T > &avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > &avoid_edges, std::list< T > &previousPath, std::list< T > &altPath, int &altDrivingTime, int &altWalkingTime, T &altParkingNodeId)
Given a driving-walking path, this function calculates the best alternative path with the same constraints. The function works by avoiding each of the edges in the path at a time and calculating the best path with the new restriction, using the EnvironmentallyFriendly algorithm which has time complexity of O(log(V)(E+V)). The total complexity is: O(Vlog(V)(E+V)) where V is the number of vertices and E is the number of edges since the maximum number of edges in a path is V-1.
template<class T>
std::string AlternativeRoutes (const Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, const int maxWalkTime, const std::unordered_set< T > &avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > &avoid_edges, std::list< T > &path1, T &parkingNodeId1, int &walkingTime1, int &drivingTime1, std::list< T > &path2, T &parkingNodeId2, int &walkingTime2, int &drivingTime2)
Given that no path was found with the constraints, this function tries to remove each constraint one by one and find one path and an alternative to it with the same constraints. The order by which constraints are removed is the following:
Function Documentation
AlternativeRoutes()
template<class T> std::string AlternativeRoutes (const Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, const int maxWalkTime, const std::unordered_set< T > & avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > & avoid_edges, std::list< T > & path1, T & parkingNodeId1, int & walkingTime1, int & drivingTime1, std::list< T > & path2, T & parkingNodeId2, int & walkingTime2, int & drivingTime2)
Given that no path was found with the constraints, this function tries to remove each constraint one by one and find one path and an alternative to it with the same constraints. The order by which constraints are removed is the following:
Maximum walking time constraint
Edge avoidance constraint
Node avoidance constraint
Maximum walking time and edge avoidance constraints
Maximum walking time and node avoidance constraints
Node and edge avoidance constraints
No constraints, except that the path must include driving and walking segments (must include a parking node which isn't the source or destination)
Template Parameters
T
Parameters
g graph where the path is calculated
source vertex that the path starts in
dest vertex where the path ends
maxWalkTime maximum allowed walking time
avoid_nodes nodes that the path can't go through
avoid_edges edges that the path can't go through
path1 used to return the first alternative path as list of node ids
parkingNodeId1 used to return the parking node id of the first alternative path
walkingTime1 used to return the walking time of the first alternative path
drivingTime1 used to return the driving time of the first alternative path
path2 used to return the second alternative path as list of node ids
parkingNodeId2 used to return the parking node id of the second alternative path
walkingTime2 used to return the walking time of the second alternative path
drivingTime2 used to return the driving time of the second alternative path
Returns
std::string returns a message indicating the constraints that were removed to find the alternative paths
Definition at line 113 of file AlternativeRoutes.cpp.
References calculateEnvironmentallyFriendlyPath(), copyIfBetter(), and getBestAlternative().
Referenced by EFriendlyRoute(), and processBatchMode().
copyIfBetter()
template<class T> void copyIfBetter (std::list< T > & path1, T & parkingNodeId1, int & walkingTime1, int & drivingTime1, std::list< T > & path2, T & parkingNodeId2, int & walkingTime2, int & drivingTime2)
Copies path 2, parking node 2, walking time 2, and driving time 2 to path 1, parking node 1, walking time 1 and driving time 1 if path 2 is better (smaller total cost) in O(L) where L is the size of path2.
Template Parameters
T
Parameters
path1 list of node ids representing path 1
parkingNodeId1 Id of the parking node of path 1
walkingTime1 walking time of path 1
drivingTime1 driving time of path 1
path2
parkingNodeId2
walkingTime2
drivingTime2
Definition at line 20 of file AlternativeRoutes.cpp.
Referenced by AlternativeRoutes(), and getBestAlternative().
getBestAlternative()
template<class T> void getBestAlternative (const Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, const int maxWalkTime, const std::unordered_set< T > & avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > & avoid_edges, std::list< T > & previousPath, std::list< T > & altPath, int & altDrivingTime, int & altWalkingTime, T & altParkingNodeId)
Given a driving-walking path, this function calculates the best alternative path with the same constraints. The function works by avoiding each of the edges in the path at a time and calculating the best path with the new restriction, using the EnvironmentallyFriendly algorithm which has time complexity of O(log(V)(E+V)). The total complexity is: O(Vlog(V)(E+V)) where V is the number of vertices and E is the number of edges since the maximum number of edges in a path is V-1.
Template Parameters
T
Parameters
g graph where the path is calculated
source node where the path starts
dest node where the path ends
maxWalkTime maximum walking time allowed
avoid_nodes nodes that the path can't go through
avoid_edges nodes that the path can't go through
previousPath path that will be used to calculate the alternative path
altPath used to return alternative path
altDrivingTime used to return the driving time of the alternative path
altWalkingTime used to return the walking time of the alternative path
altParkingNodeId used to return the parking node id of the alternative path
Definition at line 48 of file AlternativeRoutes.cpp.
References calculateEnvironmentallyFriendlyPath(), and copyIfBetter().
Referenced by AlternativeRoutes().