DA Project 1 - T02G06: batchmode/BatchMode.cpp File Reference
BatchMode.cpp File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <unordered_set>
#include <regex>
#include "../utils/Graph.h"
#include "../utils/RestrictedDijkstra.hpp"
#include "../utils/GetDrivingPath.hpp"
#include "../algorithms/IndependentRoutePlanning.cpp"
#include "../algorithms/RestrictedRoutePlanning.cpp"
#include "../algorithms/EnvironmentallyFriendly.cpp"
#include "../algorithms/AlternativeRoutes.cpp"
#include "../utils/GraphInitialization.cpp"
Functions
void outputSourceDest (int sourceId, int destinationId, ostream &outputFile)
Outputs the source and destination, since it's needed in the beggining of each output.
void outputPathAndCost (list< int > &path, int cost, ostream &outputFile)
Outputs the given path and cost to a file. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
void parseDrivingWalkingPath (list< int > &path, int parkingNodeId, list< int > &drivingPath, list< int > &walkingPath)
Splits a driving and walking path into two separate lists. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
void outputDrivingWalkingPath (list< int > &path, int parkingNodeId, ostream &outputFile, int &drivingTime, int &walkingTime, string mode)
Outputs the driving and walking portions of a path to a file. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
void processBatchMode (Graph< int > &graph)
Processes a batch mode operation for route planning.
Function Documentation
outputDrivingWalkingPath()
void outputDrivingWalkingPath (list< int > & path, int parkingNodeId, ostream & outputFile, int & drivingTime, int & walkingTime, string mode)
Outputs the driving and walking portions of a path to a file. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
Parameters
path The full path including driving and walking sections.
parkingNodeId The node where the switch from driving to walking occurs.
outputFile The output file stream.
drivingTime The time taken for the driving portion.
walkingTime The time taken for the walking portion.
mode The mode identifier for the output.
Definition at line 92 of file BatchMode.cpp.
References outputPathAndCost(), and parseDrivingWalkingPath().
Referenced by EFriendlyRoute(), and processBatchMode().
outputPathAndCost()
void outputPathAndCost (list< int > & path, int cost, ostream & outputFile)
Outputs the given path and cost to a file. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
Parameters
path The list of nodes representing the path.
cost The total cost of the path.
outputFile The output file stream.
Definition at line 41 of file BatchMode.cpp.
Referenced by independentRoute(), outputDrivingWalkingPath(), processBatchMode(), and restrictedRoute().
outputSourceDest()
void outputSourceDest (int sourceId, int destinationId, ostream & outputFile)
Outputs the source and destination, since it's needed in the beggining of each output.
Parameters
sourceId The id of the source node
destinationId The id of the destination node
outputFile The output file stream.
Definition at line 28 of file BatchMode.cpp.
Referenced by independentRoute(), processBatchMode(), and restrictedRoute().
parseDrivingWalkingPath()
void parseDrivingWalkingPath (list< int > & path, int parkingNodeId, list< int > & drivingPath, list< int > & walkingPath)
Splits a driving and walking path into two separate lists. Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
Parameters
path The full path including both driving and walking sections.
parkingNodeId The node where the switch from driving to walking occurs.
drivingPath The list to store the driving portion of the path.
walkingPath The list to store the walking portion of the path.
Definition at line 64 of file BatchMode.cpp.
Referenced by outputDrivingWalkingPath().
processBatchMode()
void processBatchMode (Graph< int > & graph)
Processes a batch mode operation for route planning.
Reads input from "batchmode/input.txt", processes the data, and writes the output to "batchmode/output.txt". Supports different routing modes and constraints.
Parameters
graph The graph representing the road network.
Definition at line 116 of file BatchMode.cpp.
References AlternativeRoutes(), calculateEnvironmentallyFriendlyPath(), Graph< T >::findVertexById(), IndependentRoutePlanning(), outputDrivingWalkingPath(), outputPathAndCost(), outputSourceDest(), and RestrictedRoutePlanning().
Referenced by runBatchMode().