DA Project 1 - T02G06: algorithms/EnvironmentallyFriendly.cpp File Reference
EnvironmentallyFriendly.cpp File Reference
#include "../utils/Graph.h"
#include "../utils/GraphInitialization.cpp"
#include "../utils/PairHash.hpp"
#include "../utils/GetDrivingPath.hpp"
#include <unordered_set>
#include <list>
Functions
template<class T>
int walkingReverseDijsktra (const Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, const int maxWalkTime, const std::unordered_set< T > &avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > &avoid_edges, std::unordered_map< Vertex< T > *, double > &reacheableVertices, std::vector< Vertex< T > * > &visitedVertices)
Performs a Dijkstra's algorithm from source backwards (in the incoming edges of each node) using as distance the walking distance. Total complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
template<class T>
Vertex< T > * drivingDijkstra (const Graph< T > &g, Vertex< T > *source, const std::unordered_set< T > &avoidNodes, const std::unordered_set< std::pair< T, T >, pairHash > &avoidEdges, std::unordered_map< Vertex< T > *, double > &reacheableWalkingVertices, int &walkingTime, int &drivingTime, std::vector< Vertex< T > * > &visitedVertices)
After a walkingReverseDijsktra is performed, this function performs a driving Dijkstra starting at source. This also keeps track of the total time needed to traverse a path that parks at each of the nodes in reacheableWalkingNodes, and the node that minimizes that total time will be considered the parking node. The total complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
template<class T>
void getDrivingAndWalkingPath (Vertex< T > *parkingNode, std::list< T > &orderedIds)
After driving and walking Dijkstra are performed, this function fetches the best path in O(V) time complexity where V is the number of vertices in the graph.
template<class T>
int calculateEnvironmentallyFriendlyPath (const Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, const int maxWalkTime, const std::unordered_set< T > &avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > &avoid_edges, std::list< T > &path, T &parkingNodeId, int &walkingTime, int &drivingTime)
Performs a walking and a driving Dijkstra to find the best path from source to dest that includes driving and walking segments. Total time complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
Function Documentation
calculateEnvironmentallyFriendlyPath()
template<class T> int calculateEnvironmentallyFriendlyPath (const Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, const int maxWalkTime, const std::unordered_set< T > & avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > & avoid_edges, std::list< T > & path, T & parkingNodeId, int & walkingTime, int & drivingTime)
Performs a walking and a driving Dijkstra to find the best path from source to dest that includes driving and walking segments. Total time complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
Template Parameters
T
Parameters
g
source vertex where the path starts
dest vertex where the path ends
maxWalkTime maximum walking distance allowed
avoid_nodes nodes that the path can't go through
avoid_edges edges that the path can't go through
path used to return the best path as a list of ordered IDs
parkingNodeId used to return the ID of the node where the user should park
walkingTime used to return the walking time of the best path
drivingTime used to return the driving time of the best path
Returns
int is 0 if a path was found, -1 otherwise
Definition at line 180 of file EnvironmentallyFriendly.cpp.
References cleanUpPaths(), drivingDijkstra(), getDrivingAndWalkingPath(), Vertex< T >::getId(), and walkingReverseDijsktra().
Referenced by AlternativeRoutes(), EFriendlyRoute(), getBestAlternative(), and processBatchMode().
drivingDijkstra()
template<class T> Vertex< T > * drivingDijkstra (const Graph< T > & g, Vertex< T > * source, const std::unordered_set< T > & avoidNodes, const std::unordered_set< std::pair< T, T >, pairHash > & avoidEdges, std::unordered_map< Vertex< T > *, double > & reacheableWalkingVertices, int & walkingTime, int & drivingTime, std::vector< Vertex< T > * > & visitedVertices)
After a walkingReverseDijsktra is performed, this function performs a driving Dijkstra starting at source. This also keeps track of the total time needed to traverse a path that parks at each of the nodes in reacheableWalkingNodes, and the node that minimizes that total time will be considered the parking node. The total complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
Template Parameters
T
Parameters
g graph
source the node from which the Dijkstra will be performed
avoidNodes nodes that the path can't go through
avoidEdges edges that the path can't go through
reacheableWalkingVertices map between the ids of nodes that are candidates to be parking nodes and the time needed to walk to them from source
walkingTime used to return the walking time of the best path
drivingTime used to return the driving time of the best path
visitedVertices vertices that the Dijsktra visited
Returns
Vertex<T>*
Definition at line 90 of file EnvironmentallyFriendly.cpp.
References cleanUpVisitedAndDist(), MutablePriorityQueue< T >::decreaseKey(), MutablePriorityQueue< T >::empty(), MutablePriorityQueue< T >::extractMin(), Vertex< T >::getAdj(), Vertex< T >::getDist(), Vertex< T >::getId(), MutablePriorityQueue< T >::insert(), Vertex< T >::isProcessing(), Vertex< T >::isVisited(), Vertex< T >::setDist(), Vertex< T >::setPath(), Vertex< T >::setProcessing(), and Vertex< T >::setVisited().
Referenced by calculateEnvironmentallyFriendlyPath().
getDrivingAndWalkingPath()
template<class T> void getDrivingAndWalkingPath (Vertex< T > * parkingNode, std::list< T > & orderedIds)
After driving and walking Dijkstra are performed, this function fetches the best path in O(V) time complexity where V is the number of vertices in the graph.
Template Parameters
T
Parameters
parkingNode node where the user parks and starts walking
orderedIds used to return the ordered ids of nodes in the path
Definition at line 149 of file EnvironmentallyFriendly.cpp.
References Edge< T >::getDest(), getDrivingPath(), and Vertex< T >::getWalkingPath().
Referenced by calculateEnvironmentallyFriendlyPath().
walkingReverseDijsktra()
template<class T> int walkingReverseDijsktra (const Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, const int maxWalkTime, const std::unordered_set< T > & avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > & avoid_edges, std::unordered_map< Vertex< T > *, double > & reacheableVertices, std::vector< Vertex< T > * > & visitedVertices)
Performs a Dijkstra's algorithm from source backwards (in the incoming edges of each node) using as distance the walking distance. Total complexity is O((V+E)logV) where V is the number of vertices and E is the number of edges in the graph.
Template Parameters
T
Parameters
g graph where the Dijkstra will be performed.
source node from which the Dijkstra will be calculated. Should be the destination of the path.
maxWalkTime maximum walking time allowed.
avoid_nodes nodes that the path can't go through.
avoid_edges edges that the path can't go through.
reacheableVertices map that relates ids of vertices and the time needed to reach source from them walking. Only nodes which have parking spots and that are at a walking distance smaller than maxWalkTime are included.
visitedVertices should be initialized as an empty vector. It will contain all the vertices visited during the algorithm.
Returns
int returns 0 as success, -1 if no reacheable vertices were found.
Definition at line 25 of file EnvironmentallyFriendly.cpp.
References cleanUpVisitedAndDist(), MutablePriorityQueue< T >::decreaseKey(), MutablePriorityQueue< T >::empty(), MutablePriorityQueue< T >::extractMin(), Vertex< T >::getDist(), Vertex< T >::getId(), Vertex< T >::getIncoming(), Vertex< T >::getParking(), MutablePriorityQueue< T >::insert(), Vertex< T >::isProcessing(), Vertex< T >::isVisited(), Vertex< T >::setDist(), Vertex< T >::setProcessing(), Vertex< T >::setVisited(), and Vertex< T >::setWalkingPath().
Referenced by calculateEnvironmentallyFriendlyPath().