DA Project 1 - T02G06: utils/GetDrivingPath.hpp File Reference
GetDrivingPath.hpp File Reference
#include "Graph.h"
#include <list>
Functions
template<class T>
void getDrivingPath (Vertex< T > *destNode, std::list< T > &orderedIds)
Read the path that leads to a vertex from the vertices Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
Function Documentation
getDrivingPath()
template<class T> void getDrivingPath (Vertex< T > * destNode, std::list< T > & orderedIds)
Read the path that leads to a vertex from the vertices Runs in O(V) time where V is the number of vertices in the graph because the path's length is at most V-1.
Template Parameters
T template parameter related to the type of vertice
Parameters
destNode Last vertice on the path
orderedIds initialized list where the ids of the vertices on the path will be put
Definition at line 15 of file GetDrivingPath.hpp.
References Vertex< T >::getId(), Edge< T >::getOrig(), and Vertex< T >::getPath().
Referenced by getDrivingAndWalkingPath(), IndependentRoutePlanning(), and RestrictedRoutePlanning().