DA Project 1 - T02G06: utils/Graph.h File Reference
Graph.h File Reference
#include <iostream>
#include <vector>
#include <queue>
#include <limits>
#include <algorithm>
#include <string>
#include "MutablePriorityQueue.h"
Classes
class Vertex< T >
class Edge< T >
class Graph< T >
Macros
#define INF std::numeric_limits<double>::max()const T &in
Functions
void deleteMatrix (int **m, int n)
void deleteMatrix (double **m, int n)
template<class T>
void cleanUpVisitedAndDist (const std::vector< Vertex< T > * > &visitedVertices)
Cleans the visited and dist fields of vertices.
template<class T>
void cleanUpPaths (const std::vector< Vertex< T > * > &visitedVertices)
Cleans the path fields of vertices.
Macro Definition Documentation
INF
#define INF std::numeric_limits<double>::max()const T &in
Definition at line 18 of file Graph.h.
Function Documentation
cleanUpPaths()
template<class T> void cleanUpPaths (const std::vector< Vertex< T > * > & visitedVertices)
Cleans the path fields of vertices.
Template Parameters
T
Parameters
visitedVertices Vertices that were affected by the Dijkstra
Definition at line 616 of file Graph.h.
Referenced by calculateEnvironmentallyFriendlyPath(), IndependentRoutePlanning(), and RestrictedRoutePlanning().
cleanUpVisitedAndDist()
template<class T> void cleanUpVisitedAndDist (const std::vector< Vertex< T > * > & visitedVertices)
Cleans the visited and dist fields of vertices.
Template Parameters
T
Parameters
visitedVertices Vertices that were affected by the Dijkstra
Definition at line 601 of file Graph.h.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
deleteMatrix() [1/2]
void deleteMatrix (double ** m, int n) inline
Definition at line 579 of file Graph.h.
deleteMatrix() [2/2]
void deleteMatrix (int ** m, int n) inline
Definition at line 570 of file Graph.h.
Referenced by Graph< T >::~Graph().