DA Project 1 - T02G06: utils/GraphInitialization.cpp File Reference
GraphInitialization.cpp File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include "Graph.h"
#include <limits>
Functions
void readParseLocations (Graph< int > &g)
Reads location data from a CSV file and adds it to the graph. Works in O(V) where V is the number of vertices.
void readParseDistances (Graph< int > &g)
Reads distance data from a CSV file and adds edges to the graph. Works in O(E) where E is the number of edges.
Function Documentation
readParseDistances()
void readParseDistances (Graph< int > & g)
Reads distance data from a CSV file and adds edges to the graph. Works in O(E) where E is the number of edges.
Extracts locations, driving time, and walking time from datasets/distances.csv and adds bidirectional edges to the graph.
Parameters
g Reference to the Graph object.
Definition at line 55 of file GraphInitialization.cpp.
References Graph< T >::addBidirectionalEdge().
Referenced by main(), and runBatchMode().
readParseLocations()
void readParseLocations (Graph< int > & g)
Reads location data from a CSV file and adds it to the graph. Works in O(V) where V is the number of vertices.
Extracts location name, ID, code, and parking availability from datasets/locations.csv and adds vertices to the graph.
Parameters
g Reference to the Graph object.
Definition at line 20 of file GraphInitialization.cpp.
References Graph< T >::addVertex().
Referenced by main(), and runBatchMode().