DA Project 1 - T02G06: algorithms/IndependentRoutePlanning.cpp File Reference
IndependentRoutePlanning.cpp File Reference
#include "../utils/RestrictedDijkstra.hpp"
#include "../utils/GetDrivingPath.hpp"
#include <list>
#include <vector>
Functions
template<class T>
void IndependentRoutePlanning (Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, std::list< T > &bestPath, int &bestTime, std::list< T > &altPath, int &altTime)
Calculates the shortest path and an alternative path between two vertices in a graph. The time complexity of the function is O((V + E) log V) for each call to Restricted Dijkstra, where V is the number of vertices and E is the number of edges in the graph. Since Restricted Dijkstra is called twice (once for the best path and once for the alternative path), the overall complexity is O(2 * (V + E) log V), which simplifies to O((V + E) log V).
Function Documentation
IndependentRoutePlanning()
template<class T> void IndependentRoutePlanning (Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, std::list< T > & bestPath, int & bestTime, std::list< T > & altPath, int & altTime)
Calculates the shortest path and an alternative path between two vertices in a graph. The time complexity of the function is O((V + E) log V) for each call to Restricted Dijkstra, where V is the number of vertices and E is the number of edges in the graph. Since Restricted Dijkstra is called twice (once for the best path and once for the alternative path), the overall complexity is O(2 * (V + E) log V), which simplifies to O((V + E) log V).
Template Parameters
T The type of the vertex identifiers (e.g., int, string).
Parameters
g The graph where the paths are calculated.
source Pointer to the source vertex.
dest Pointer to the destination vertex.
bestPath Reference to a list where the best path (shortest path) will be stored.
bestTime Reference to an integer where the time of the best path will be stored.
altPath Reference to a list where the alternative path will be stored.
altTime Reference to an integer where the time of the alternative path will be stored.
Definition at line 22 of file IndependentRoutePlanning.cpp.
References cleanUpPaths(), getDrivingPath(), Vertex< T >::getId(), and RestrictedDijkstra().
Referenced by independentRoute(), and processBatchMode().