DA Project 1 - T02G06: utils/RestrictedDijkstra.hpp File Reference
RestrictedDijkstra.hpp File Reference
#include "../utils/Graph.h"
#include "../utils/PairHash.hpp"
#include <unordered_set>
Functions
template<class T>
int RestrictedDijkstra (const Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, const std::unordered_set< T > &avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > &avoid_edges, std::vector< Vertex< T > * > &visitedVertices)
Runs a Dijkstra algorithm on a graph, finding a path from the source to the dest node, while avoiding certain nodes and edges. Total time complexity is O(log(V)(E+V)) where V is the number of vertices and E is the number of edges.
Function Documentation
RestrictedDijkstra()
template<class T> int RestrictedDijkstra (const Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, const std::unordered_set< T > & avoid_nodes, const std::unordered_set< std::pair< T, T >, pairHash > & avoid_edges, std::vector< Vertex< T > * > & visitedVertices)
Runs a Dijkstra algorithm on a graph, finding a path from the source to the dest node, while avoiding certain nodes and edges. Total time complexity is O(log(V)(E+V)) where V is the number of vertices and E is the number of edges.
Template Parameters
T
Parameters
g graph where the path will be found
source Initial node of the path
dest Final node of the path
avoid_nodes nodes that the path can't go through
avoid_edges edges that the path can't go through
Definition at line 18 of file RestrictedDijkstra.hpp.
References cleanUpVisitedAndDist(), MutablePriorityQueue< T >::decreaseKey(), MutablePriorityQueue< T >::empty(), MutablePriorityQueue< T >::extractMin(), Vertex< T >::getAdj(), Vertex< T >::getDist(), Vertex< T >::getId(), MutablePriorityQueue< T >::insert(), Vertex< T >::isProcessing(), Vertex< T >::isVisited(), Vertex< T >::setDist(), Vertex< T >::setPath(), Vertex< T >::setProcessing(), and Vertex< T >::setVisited().
Referenced by IndependentRoutePlanning(), and RestrictedRoutePlanning().