DA Project 1 - T02G06: algorithms/RestrictedRoutePlanning.cpp File Reference
RestrictedRoutePlanning.cpp File Reference
#include "../utils/RestrictedDijkstra.hpp"
#include "../utils/GetDrivingPath.hpp"
#include <list>
Functions
template<class T>
int RestrictedRoutePlanning (Graph< T > &g, Vertex< T > *source, Vertex< T > *dest, std::unordered_set< T > avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > avoid_edges, Vertex< T > *include_node, std::list< T > &path)
This function computes the shortest path between the source and destination vertices, considering:
Function Documentation
RestrictedRoutePlanning()
template<class T> int RestrictedRoutePlanning (Graph< T > & g, Vertex< T > * source, Vertex< T > * dest, std::unordered_set< T > avoid_nodes, std::unordered_set< std::pair< T, T >, pairHash > avoid_edges, Vertex< T > * include_node, std::list< T > & path)
This function computes the shortest path between the source and destination vertices, considering:
Nodes to avoid.
Edges to avoid.
An optional intermediate node that must be included in the path. The time complexity of the function is O((V + E) log V) for each call to Restricted Dijkstra, where V is the number of vertices and E is the number of edges in the graph. If the include_node is specified, Restricted Dijkstra is called twice, resulting in an overall complexity of O(2 * (V + E) log V), which simplifies to O((V + E) log V).
Template Parameters
T The type of the vertex identifiers (e.g., int, string).
Parameters
g The graph where the path is calculated.
source Pointer to the source vertex.
dest Pointer to the destination vertex.
avoid_nodes A set of nodes that must be avoided in the path.
avoid_edges A set of edges that must be avoided in the path.
include_node Pointer to an intermediate node that must be included in the path (can be nullptr if not required).
path Reference to a list where the resulting path will be stored.
Returns
int The total time of the path (sum of weights), or -1 if no valid path is found.
Definition at line 29 of file RestrictedRoutePlanning.cpp.
References cleanUpPaths(), getDrivingPath(), and RestrictedDijkstra().
Referenced by processBatchMode(), and restrictedRoute().