DA Project 1 - T02G06: Graph< T > Class Template Reference
Graph< T > Class Template Reference
#include <Graph.h>
Public Member Functions
~Graph ()
Vertex< T > * findVertex (std::string code) const
Vertex< T > * findVertexById (T id) const
Find a vertex by its id.
bool addVertex (std::string location, const T &id, std::string code, bool parking)
bool removeVertex (const T &in)
bool addEdge (std::string &sourc, std::string &dest, int driving, int walking)
bool removeEdge (const T &source, const T &dest)
bool addBidirectionalEdge (const std::string &sourc, const std::string &dest, int drivingTime, int walkingTime)
int getNumVertex () const
std::vector< Vertex< T > * > getVertexSet () const
void printVertices () const
void printEdges () const
Protected Member Functions
int findVertexIdx (const T &in) const
Protected Attributes
std::vector< Vertex< T > * > vertexSet
double ** distMatrix = nullptr
int ** pathMatrix = nullptr
Detailed Description
template<class T>
class Graph< T >
Definition at line 119 of file Graph.h.
Constructor & Destructor Documentation
~Graph()
template<class T> Graph< T >::~Graph ()
Definition at line 589 of file Graph.h.
References deleteMatrix(), distMatrix, pathMatrix, and vertexSet.
Member Function Documentation
addBidirectionalEdge()
template<class T> bool Graph< T >::addBidirectionalEdge (const std::string & sourc, const std::string & dest, int drivingTime, int walkingTime)
Definition at line 528 of file Graph.h.
References findVertex().
Referenced by readParseDistances().
addEdge()
template<class T> bool Graph< T >::addEdge (std::string & sourc, std::string & dest, int driving, int walking)
Definition at line 504 of file Graph.h.
References findVertex().
addVertex()
template<class T> bool Graph< T >::addVertex (std::string location, const T & id, std::string code, bool parking)
Definition at line 469 of file Graph.h.
References findVertex(), and vertexSet.
Referenced by readParseLocations().
findVertex()
template<class T> Vertex< T > * Graph< T >::findVertex (std::string code) const
Definition at line 436 of file Graph.h.
References vertexSet.
Referenced by addBidirectionalEdge(), addEdge(), addVertex(), and removeEdge().
findVertexById()
template<class T> Vertex< T > * Graph< T >::findVertexById (T id) const
Find a vertex by its id.
Definition at line 447 of file Graph.h.
References vertexSet.
Referenced by processBatchMode(), readSourceAndDest(), and restrictedRoute().
findVertexIdx()
template<class T> int Graph< T >::findVertexIdx (const T & in) const protected
Definition at line 458 of file Graph.h.
References vertexSet.
getNumVertex()
template<class T> int Graph< T >::getNumVertex () const
Definition at line 423 of file Graph.h.
References vertexSet.
getVertexSet()
template<class T> std::vector< Vertex< T > * > Graph< T >::getVertexSet () const
Definition at line 428 of file Graph.h.
References vertexSet.
printEdges()
template<class T> void Graph< T >::printEdges () const
Definition at line 555 of file Graph.h.
References vertexSet.
printVertices()
template<class T> void Graph< T >::printVertices () const
Definition at line 541 of file Graph.h.
References vertexSet.
removeEdge()
template<class T> bool Graph< T >::removeEdge (const T & source, const T & dest)
Definition at line 519 of file Graph.h.
References findVertex(), and Vertex< T >::removeEdge().
removeVertex()
template<class T> bool Graph< T >::removeVertex (const T & in)
Definition at line 482 of file Graph.h.
References vertexSet.
Member Data Documentation
distMatrix
template<class T> double** Graph< T >::distMatrix = nullptr protected
Definition at line 158 of file Graph.h.
Referenced by ~Graph().
pathMatrix
template<class T> int** Graph< T >::pathMatrix = nullptr protected
Definition at line 159 of file Graph.h.
Referenced by ~Graph().
vertexSet
template<class T> std::vector<Vertex<T> *> Graph< T >::vertexSet protected
Definition at line 156 of file Graph.h.
Referenced by addVertex(), findVertex(), findVertexById(), findVertexIdx(), getNumVertex(), getVertexSet(), printEdges(), printVertices(), removeVertex(), and ~Graph().
The documentation for this class was generated from the following file:
utils/Graph.h