DA Project 1 - T02G06: Vertex< T > Class Template Reference
Vertex< T > Class Template Reference
#include <Graph.h>
Public Member Functions
Vertex (std::string location, T id, std::string code, bool parking)
bool operator< (Vertex< T > &vertex) const
T getId () const
std::string getLocation () const
std::string getCode () const
bool getParking () const
std::vector< Edge< T > * > getAdj () const
bool isVisited () const
bool isProcessing () const
unsigned int getIndegree () const
int getDist () const
Edge< T > * getPath () const
Edge< T > * getWalkingPath () const
std::vector< Edge< T > * > getIncoming () const
void setId (T id)
void setVisited (bool visited)
void setProcessing (bool processing)
int getLow () const
void setLow (int value)
int getNum () const
void setNum (int value)
void setIndegree (unsigned int indegree)
void setDist (int dist)
void setPath (Edge< T > *path)
void setWalkingPath (Edge< T > *path)
Edge< T > * addEdge (Vertex< T > *dest, int driving, int walking)
bool removeEdge (T in)
void removeOutgoingEdges ()
Protected Member Functions
void deleteEdge (Edge< T > *edge)
Protected Attributes
std::string location = ""
T id
std::string code = ""
bool parking = false
std::vector< Edge< T > * > adj
bool visited = false
bool processing = false
int low = -1
int num = -1
unsigned int indegree
int dist = std::numeric_limits<int>::max()
Edge< T > * path = nullptr
Edge< T > * walkingPath = nullptr
std::vector< Edge< T > * > incoming
int queueIndex = 0
Friends
class MutablePriorityQueue< Vertex >
Detailed Description
template<class T>
class Vertex< T >
Definition at line 23 of file Graph.h.
Constructor & Destructor Documentation
Vertex()
template<class T> Vertex< T >::Vertex (std::string location, T id, std::string code, bool parking)
Definition at line 178 of file Graph.h.
References code, id, location, and parking.
Referenced by addEdge(), deleteEdge(), MutablePriorityQueue< Vertex >, operator<(), and removeEdge().
Member Function Documentation
addEdge()
template<class T> Edge< T > * Vertex< T >::addEdge (Vertex< T > * dest, int driving, int walking)
Definition at line 185 of file Graph.h.
References adj, incoming, and Vertex().
deleteEdge()
template<class T> void Vertex< T >::deleteEdge (Edge< T > * edge) protected
Definition at line 350 of file Graph.h.
References Edge< T >::getDest(), incoming, and Vertex().
Referenced by removeEdge(), and removeOutgoingEdges().
getAdj()
template<class T> std::vector< Edge< T > * > Vertex< T >::getAdj () const
Definition at line 275 of file Graph.h.
References adj.
Referenced by drivingDijkstra(), and RestrictedDijkstra().
getCode()
template<class T> std::string Vertex< T >::getCode () const
Definition at line 245 of file Graph.h.
References code.
getDist()
template<class T> int Vertex< T >::getDist () const
Definition at line 295 of file Graph.h.
References dist.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
getId()
template<class T> T Vertex< T >::getId () const
Definition at line 235 of file Graph.h.
References id.
Referenced by calculateEnvironmentallyFriendlyPath(), drivingDijkstra(), getDrivingPath(), independentRoute(), IndependentRoutePlanning(), removeEdge(), RestrictedDijkstra(), restrictedRoute(), and walkingReverseDijsktra().
getIncoming()
template<class T> std::vector< Edge< T > * > Vertex< T >::getIncoming () const
Definition at line 310 of file Graph.h.
References incoming.
Referenced by walkingReverseDijsktra().
getIndegree()
template<class T> unsigned int Vertex< T >::getIndegree () const
Definition at line 290 of file Graph.h.
References indegree.
getLocation()
template<class T> std::string Vertex< T >::getLocation () const
Definition at line 240 of file Graph.h.
References location.
getLow()
template<class T> int Vertex< T >::getLow () const
Definition at line 255 of file Graph.h.
References low.
getNum()
template<class T> int Vertex< T >::getNum () const
Definition at line 265 of file Graph.h.
References num.
getParking()
template<class T> bool Vertex< T >::getParking () const
Definition at line 250 of file Graph.h.
References parking.
Referenced by walkingReverseDijsktra().
getPath()
template<class T> Edge< T > * Vertex< T >::getPath () const
Definition at line 300 of file Graph.h.
References path.
Referenced by getDrivingPath().
getWalkingPath()
template<class T> Edge< T > * Vertex< T >::getWalkingPath () const
Definition at line 305 of file Graph.h.
References walkingPath.
Referenced by getDrivingAndWalkingPath().
isProcessing()
template<class T> bool Vertex< T >::isProcessing () const
Definition at line 285 of file Graph.h.
References processing.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
isVisited()
template<class T> bool Vertex< T >::isVisited () const
Definition at line 280 of file Graph.h.
References visited.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
operator<()
template<class T> bool Vertex< T >::operator< (Vertex< T > & vertex) const
Definition at line 230 of file Graph.h.
References dist, and Vertex().
removeEdge()
template<class T> bool Vertex< T >::removeEdge (T in)
Definition at line 198 of file Graph.h.
References adj, deleteEdge(), Edge< T >::getDest(), getId(), and Vertex().
Referenced by Graph< T >::removeEdge().
removeOutgoingEdges()
template<class T> void Vertex< T >::removeOutgoingEdges ()
Definition at line 220 of file Graph.h.
References adj, and deleteEdge().
setDist()
template<class T> void Vertex< T >::setDist (int dist)
Definition at line 335 of file Graph.h.
References dist.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
setId()
template<class T> void Vertex< T >::setId (T id)
Definition at line 315 of file Graph.h.
setIndegree()
template<class T> void Vertex< T >::setIndegree (unsigned int indegree)
Definition at line 330 of file Graph.h.
References indegree.
setLow()
template<class T> void Vertex< T >::setLow (int value)
Definition at line 260 of file Graph.h.
References low.
setNum()
template<class T> void Vertex< T >::setNum (int value)
Definition at line 270 of file Graph.h.
References num.
setPath()
template<class T> void Vertex< T >::setPath (Edge< T > * path)
Definition at line 340 of file Graph.h.
References path.
Referenced by drivingDijkstra(), and RestrictedDijkstra().
setProcessing()
template<class T> void Vertex< T >::setProcessing (bool processing)
Definition at line 325 of file Graph.h.
References processing.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
setVisited()
template<class T> void Vertex< T >::setVisited (bool visited)
Definition at line 320 of file Graph.h.
References visited.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
setWalkingPath()
template<class T> void Vertex< T >::setWalkingPath (Edge< T > * path)
Definition at line 345 of file Graph.h.
References path, and walkingPath.
Referenced by walkingReverseDijsktra().
Friends And Related Symbol Documentation
MutablePriorityQueue< Vertex >
template<class T> friend class MutablePriorityQueue< Vertex > friend
Definition at line 56 of file Graph.h.
References Vertex().
Member Data Documentation
adj
template<class T> std::vector<Edge<T> *> Vertex< T >::adj protected
Definition at line 65 of file Graph.h.
Referenced by addEdge(), getAdj(), removeEdge(), and removeOutgoingEdges().
code
template<class T> std::string Vertex< T >::code = "" protected
Definition at line 63 of file Graph.h.
Referenced by getCode(), and Vertex().
dist
template<class T> int Vertex< T >::dist = std::numeric_limits<int>::max() protected
Definition at line 72 of file Graph.h.
Referenced by getDist(), operator<(), and setDist().
id
template<class T> T Vertex< T >::id protected
Definition at line 62 of file Graph.h.
Referenced by getId(), and Vertex().
incoming
template<class T> std::vector<Edge<T> *> Vertex< T >::incoming protected
Definition at line 76 of file Graph.h.
Referenced by addEdge(), deleteEdge(), and getIncoming().
indegree
template<class T> unsigned int Vertex< T >::indegree protected
Definition at line 71 of file Graph.h.
Referenced by getIndegree(), and setIndegree().
location
template<class T> std::string Vertex< T >::location = "" protected
Definition at line 61 of file Graph.h.
Referenced by getLocation(), and Vertex().
low
template<class T> int Vertex< T >::low = -1 protected
Definition at line 70 of file Graph.h.
Referenced by getLow(), and setLow().
num
template<class T> int Vertex< T >::num = -1 protected
Definition at line 70 of file Graph.h.
Referenced by getNum(), and setNum().
parking
template<class T> bool Vertex< T >::parking = false protected
Definition at line 64 of file Graph.h.
Referenced by getParking(), and Vertex().
path
template<class T> Edge<T>* Vertex< T >::path = nullptr protected
Definition at line 73 of file Graph.h.
Referenced by getPath(), setPath(), and setWalkingPath().
processing
template<class T> bool Vertex< T >::processing = false protected
Definition at line 69 of file Graph.h.
Referenced by isProcessing(), and setProcessing().
queueIndex
template<class T> int Vertex< T >::queueIndex = 0 protected
Definition at line 78 of file Graph.h.
visited
template<class T> bool Vertex< T >::visited = false protected
Definition at line 68 of file Graph.h.
Referenced by isVisited(), and setVisited().
walkingPath
template<class T> Edge<T>* Vertex< T >::walkingPath = nullptr protected
Definition at line 74 of file Graph.h.
Referenced by getWalkingPath(), and setWalkingPath().
The documentation for this class was generated from the following file:
utils/Graph.h