DA Project 1 - T02G06: Edge< T > Class Template Reference
Edge< T > Class Template Reference
#include <Graph.h>
Public Member Functions
Edge (Vertex< T > *orig, Vertex< T > *dest, int drivingTime, int walkingTime)
Vertex< T > * getDest () const
int getDrivingTime () const
int getWalkingTime () const
bool isSelected () const
Vertex< T > * getOrig () const
Edge< T > * getReverse () const
double getFlow () const
void setSelected (bool selected)
void setReverse (Edge< T > *reverse)
void setFlow (double flow)
Protected Attributes
Vertex< T > * orig
Vertex< T > * dest
int drivingTime
int walkingTime
bool selected = false
Edge< T > * reverse = nullptr
double flow
Detailed Description
template<class T>
class Edge< T >
Definition at line 86 of file Graph.h.
Constructor & Destructor Documentation
Edge()
template<class T> Edge< T >::Edge (Vertex< T > * orig, Vertex< T > * dest, int drivingTime, int walkingTime)
Definition at line 368 of file Graph.h.
References dest, drivingTime, orig, and walkingTime.
Referenced by getReverse(), and setReverse().
Member Function Documentation
getDest()
template<class T> Vertex< T > * Edge< T >::getDest () const
Definition at line 371 of file Graph.h.
References dest.
Referenced by Vertex< T >::deleteEdge(), getDrivingAndWalkingPath(), and Vertex< T >::removeEdge().
getDrivingTime()
template<class T> int Edge< T >::getDrivingTime () const
Definition at line 376 of file Graph.h.
References drivingTime.
getFlow()
template<class T> double Edge< T >::getFlow () const
Definition at line 401 of file Graph.h.
References flow.
getOrig()
template<class T> Vertex< T > * Edge< T >::getOrig () const
Definition at line 386 of file Graph.h.
References orig.
Referenced by getDrivingPath().
getReverse()
template<class T> Edge< T > * Edge< T >::getReverse () const
Definition at line 391 of file Graph.h.
References Edge(), and reverse.
getWalkingTime()
template<class T> int Edge< T >::getWalkingTime () const
Definition at line 381 of file Graph.h.
References walkingTime.
isSelected()
template<class T> bool Edge< T >::isSelected () const
Definition at line 396 of file Graph.h.
References selected.
setFlow()
template<class T> void Edge< T >::setFlow (double flow)
Definition at line 416 of file Graph.h.
References flow.
setReverse()
template<class T> void Edge< T >::setReverse (Edge< T > * reverse)
Definition at line 411 of file Graph.h.
References Edge(), and reverse.
setSelected()
template<class T> void Edge< T >::setSelected (bool selected)
Definition at line 406 of file Graph.h.
References selected.
Member Data Documentation
dest
template<class T> Vertex<T>* Edge< T >::dest protected
Definition at line 103 of file Graph.h.
Referenced by Edge(), and getDest().
drivingTime
template<class T> int Edge< T >::drivingTime protected
Definition at line 104 of file Graph.h.
Referenced by Edge(), and getDrivingTime().
flow
template<class T> double Edge< T >::flow protected
Definition at line 113 of file Graph.h.
Referenced by getFlow(), and setFlow().
orig
template<class T> Vertex<T>* Edge< T >::orig protected
Definition at line 102 of file Graph.h.
Referenced by Edge(), and getOrig().
reverse
template<class T> Edge<T>* Edge< T >::reverse = nullptr protected
Definition at line 111 of file Graph.h.
Referenced by getReverse(), and setReverse().
selected
template<class T> bool Edge< T >::selected = false protected
Definition at line 108 of file Graph.h.
Referenced by isSelected(), and setSelected().
walkingTime
template<class T> int Edge< T >::walkingTime protected
Definition at line 105 of file Graph.h.
Referenced by Edge(), and getWalkingTime().
The documentation for this class was generated from the following file:
utils/Graph.h