DA Project 1 - T02G06: MutablePriorityQueue< T > Class Template Reference
MutablePriorityQueue< T > Class Template Reference
#include <MutablePriorityQueue.h>
Public Member Functions
MutablePriorityQueue ()
void insert (T *x)
T * extractMin ()
void decreaseKey (T *x)
bool empty ()
Detailed Description
template<class T>
class MutablePriorityQueue< T >
class T must have: (i) accessible field int queueIndex; (ii) operator< defined.
Definition at line 19 of file MutablePriorityQueue.h.
Constructor & Destructor Documentation
MutablePriorityQueue()
template<class T> MutablePriorityQueue< T >::MutablePriorityQueue ()
Definition at line 37 of file MutablePriorityQueue.h.
Member Function Documentation
decreaseKey()
template<class T> void MutablePriorityQueue< T >::decreaseKey (T * x)
Definition at line 65 of file MutablePriorityQueue.h.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
empty()
template<class T> bool MutablePriorityQueue< T >::empty ()
Definition at line 44 of file MutablePriorityQueue.h.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
extractMin()
template<class T> T * MutablePriorityQueue< T >::extractMin ()
Definition at line 49 of file MutablePriorityQueue.h.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
insert()
template<class T> void MutablePriorityQueue< T >::insert (T * x)
Definition at line 59 of file MutablePriorityQueue.h.
Referenced by drivingDijkstra(), RestrictedDijkstra(), and walkingReverseDijsktra().
The documentation for this class was generated from the following file:
utils/MutablePriorityQueue.h