DA Project 1 - T02G06: main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "utils/Graph.h"
#include "batchmode/BatchMode.cpp"
#include <string>
#include <regex>
Functions
void displayMenu ()
Displays the main menu for the Route Planning Analysis Tool. This function prints the available options for the user to interact with the tool.
void readSourceAndDest (Graph< int > &g, Vertex< int > *&source, Vertex< int > *&destination)
Reads the source and destination vertices from user input. This function prompts the user to input the IDs of the source and destination vertices. It validates the input to ensure the vertices exist in the graph.
void independentRoute (Graph< int > &g)
Executes the independent route planning functionality.
void restrictedRoute (Graph< int > &g)
Executes the restricted route planning functionality.
void EFriendlyRoute (Graph< int > &g)
Executes the environmentally-friendly route planning functionality.
void runBatchMode (Graph< int > &g)
Executes the batch mode functionality.
int main ()
Main function and entry point of the program.
Function Documentation
displayMenu()
void displayMenu ()
Displays the main menu for the Route Planning Analysis Tool. This function prints the available options for the user to interact with the tool.
Definition at line 13 of file main.cpp.
Referenced by main().
EFriendlyRoute()
void EFriendlyRoute (Graph< int > & g)
Executes the environmentally-friendly route planning functionality.
Parameters
g Reference to the graph object.
Definition at line 154 of file main.cpp.
References AlternativeRoutes(), calculateEnvironmentallyFriendlyPath(), outputDrivingWalkingPath(), and readSourceAndDest().
Referenced by main().
independentRoute()
void independentRoute (Graph< int > & g)
Executes the independent route planning functionality.
Parameters
g Reference to the graph object.
Definition at line 54 of file main.cpp.
References Vertex< T >::getId(), IndependentRoutePlanning(), outputPathAndCost(), outputSourceDest(), and readSourceAndDest().
Referenced by main().
main()
int main ()
Main function and entry point of the program.
This function initializes the graph, displays the main menu, and handles user input to execute the selected route planning functionality. The program runs in a loop until the user chooses to exit.
Returns
int Returns 0 upon successful execution.
Definition at line 256 of file main.cpp.
References displayMenu(), EFriendlyRoute(), independentRoute(), readParseDistances(), readParseLocations(), restrictedRoute(), and runBatchMode().
readSourceAndDest()
void readSourceAndDest (Graph< int > & g, Vertex< int > *& source, Vertex< int > *& destination)
Reads the source and destination vertices from user input. This function prompts the user to input the IDs of the source and destination vertices. It validates the input to ensure the vertices exist in the graph.
Parameters
g Reference to the graph object.
source Reference to a pointer where the source vertex will be stored.
destination Reference to a pointer where the destination vertex will be stored.
Definition at line 30 of file main.cpp.
References Graph< T >::findVertexById().
Referenced by EFriendlyRoute(), independentRoute(), and restrictedRoute().
restrictedRoute()
void restrictedRoute (Graph< int > & g)
Executes the restricted route planning functionality.
Parameters
g Reference to the graph object.
Definition at line 84 of file main.cpp.
References Graph< T >::findVertexById(), Vertex< T >::getId(), outputPathAndCost(), outputSourceDest(), readSourceAndDest(), and RestrictedRoutePlanning().
Referenced by main().
runBatchMode()
void runBatchMode (Graph< int > & g)
Executes the batch mode functionality.
Parameters
g Reference to the graph object.
Definition at line 235 of file main.cpp.
References processBatchMode(), readParseDistances(), and readParseLocations().
Referenced by main().